### ISSUE TITLE
Logout shows error: ExceptionsManager.js:65 Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by walter211** [kyaroru/ReactNavDrawerRedux#2]
ExceptionsManager.js:65 Cannot read property '0' of undefined
handleException @ ExceptionsManager.js:65
handleError @ InitializeCore.js:111
reportFatalError @ error-guard.js:46
__guard @ MessageQueue.js:271
MessageQueue.callFunctionReturnFlushedQueue @ MessageQueue.js:107
(anonymous) @ debuggerWorker.js:72
ExceptionsManager.js:73 Unhandled JS Exception: Cannot read property '0' of undefined
reactConsoleErrorHandler @ ExceptionsManager.js:73
console.error @ YellowBox.js:67
logToConsole @ RCTLog.js:43
logIfNoNativeHook @ RCTLog.js:29
__callFunction @ MessageQueue.js:306
(anonymous) @ MessageQueue.js:108
__guard @ MessageQueue.js:269
MessageQueue.callFunctionReturnFlushedQueue @ MessageQueue.js:107
(anonymous) @ debuggerWorker.js:72

**Comment by kyaroru** [comment]
Fixed in https://github.com/kyaroru/ReactNavDrawerRedux/commit/a82a5be53cdcd1d84feb3ea49867d02b847f0149
